### ISSUE TITLE
Attachments on Msg table should have longer attachments max limit

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1135]
Currently set to 255 chars, should maybe be 2048?

**Comment by xislam** [comment]
hi i have a problem

(venv) islam@islam-Lenovo-ideapad-330-15ARR:~/Рабочий стол/rapidpro-master$ python manage.py migrate
Traceback (most recent call last):
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 222, in all
    return [self[alias] for alias in self]
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/islam/Рабочий стол/rapidpro-master/temba/__init__.py", line 3, in <module>
    from .temba_celery import app as celery_app  # noqa
  File "/home/islam/Рабочий стол/rapidpro-master/temba/temba_celery.py", line 28, in <module>
    raven_config = getattr(settings, "RAVEN_CONFIG", None)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'temba.settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 225, in close_all
    for alias in self:
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/islam/Рабочий стол/rapidpro-master/temba/__init__.py", line 3, in <module>
    from .temba_celery import app as celery_app  # noqa
  File "/home/islam/Рабочий стол/rapidpro-master/temba/temba_celery.py", line 28, in <module>
    raven_config = getattr(settings, "RAVEN_CONFIG", None)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'temba.settings'

**Comment by xislam** [comment]
python manage.py migrate
Traceback (most recent call last):
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "temba" is not permitted to log in


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 85, in handle
    connection.prepare_database()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 25, in prepare_database
    with self.cursor() as cursor:
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/islam/Рабочий стол/rapidpro-master/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  role "temba" is not permitted to log in

(venv) islam@islam-Lenovo-ideapad-330-15ARR:~/Рабочий стол/rapidpro-master$

**Comment by rowanseymour** [comment]
@xislam please use the developer mailing list for deployment questions. Your problem has nothing to do with this specific issue.

**Comment by xislam** [comment]
ArgumentError: error evaluating function `rgba`

**Comment by rowanseymour** [comment]
@xislam if you keep spamming unrelated PRs you'll be blocked from this repo. Please use the developer mailing list.

**Comment by rowanseymour** [comment]
So this is already `2048` in the code. We just weren't able to run this (now deleted) migration: https://github.com/nyaruka/rapidpro/blob/55081c886f318a5d43c72d4927813ba4fa137c1a/temba/msgs/migrations/0114_auto_20180126_1452.py so our prod boxes are still using `255`.

Could try converting that column again now that we archive messages and have a lot less of them, or we need to remember to fix this next time we have downtime.
