### ISSUE TITLE
how to solve 500 server error when i create flow in rapidpro

### ISSUE THREAD

**Issue by HoorAhmed25** [rapidpro/rapidpro#1497]
Traceback (most recent call last):
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hoorahmed/RapidPro/rapidpro/temba/orgs/views.py", line 147, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/smartmin/views.py", line 118, in dispatch
    return wrapper(request, *args, **kwargs)
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/smartmin/views.py", line 114, in wrapper
    return super(SmartView, self).dispatch(request, *args, **kwargs)
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/hoorahmed/RapidPro/rapidpro/temba/orgs/views.py", line 218, in form_valid
    self.save(self.object)
  File "/home/hoorahmed/RapidPro/rapidpro/temba/flows/views.py", line 449, in save
    self.object = Flow.create(
  File "/home/hoorahmed/RapidPro/rapidpro/temba/flows/models.py", line 215, in create
    flow.save_revision(
  File "/home/hoorahmed/RapidPro/rapidpro/temba/flows/models.py", line 808, in save_revision
    flow_info = mailroom.get_client().flow_inspect(self.org.id, definition)
  File "/home/hoorahmed/RapidPro/rapidpro/temba/mailroom/client.py", line 103, in flow_inspect
    return self._request("flow/inspect", payload)
  File "/home/hoorahmed/RapidPro/rapidpro/temba/mailroom/client.py", line 216, in _request
    response.raise_for_status()
  File "/home/hoorahmed/RapidPro/rapidpro/env/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8090/mr/flow/inspect

**Comment by rowanseymour** [comment]
The problem is on the mailroom side. Look in the mailroom logs to see why it returned a 500.
