### ISSUE TITLE
could not import setting                     

### ISSUE THREAD

**Issue by srinu-dipl** [rapidpro/rapidpro#160]
when i run python manage.py runserver 0.0.0.0:8000

Traceback (most recent call last):
File "manage.py", line 9, in
execute_from_command_line(sys.argv)
File "/home/administrator/projects/rapidpro/env/local/lib/python2.7/site-packages/django/core/management/init.py", line 385, in execute_from_command_line
utility.execute()
File "/home/administrator/projects/rapidpro/env/local/lib/python2.7/site-packages/django/core/management/init.py", line 345, in execute
settings.INSTALLED_APPS
File "/home/administrator/projects/rapidpro/env/local/lib/python2.7/site-packages/django/conf/init.py", line 46, in getattr
self.setup(name)
File "/home/administrator/projects/rapidpro/env/local/lib/python2.7/site-packages/django/conf/__init_.py", line 42, in setup
self.wrapped = Settings(settings_module)
File "/home/administrator/projects/rapidpro/env/local/lib/python2.7/site-packages/django/conf/__init.py", line 98, in init
% (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'temba.settings' (Is it on sys.path? Is there an import error in the settings file?): Could not import settings 'temba.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named settings

**Comment by nicpottier** [comment]
Please make sure you follow all the instructions here:
  http://rapidpro.github.io/rapidpro/docs/development/

You haven't linked in the development settings.
```
$ ln -s temba/settings.py.dev temba/settings.py
```

**Comment by srinu-dipl** [comment]
i was run above settings but following error came
ln: failed to create symbolic link ‘temba/settings.py’: File exists

**Comment by nicpottier** [comment]
From what directory are you running % python?

**Comment by eatskolnikov** [comment]
I had this problem but in the end i just made this:
```
cp temba/settings.py.dev temba/settings.py
```
Hope this can help any future soul that get this error
