### ISSUE TITLE
Rapidpro not syncdb or runserver

### ISSUE THREAD

**Issue by Haythamamin** [rapidpro/rapidpro#211]
after installing all dependenices and requiremnts trying to run sudo python manage.py syncdb or runserver result in this error. Any help would be appriciated.

me@ubuntu:~/Downloads/rapidpro$ sudo python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/amin/Downloads/rapidpro/temba/__init__.py", line 5, in <module>
    from .temba_celery import app as celery_app
  File "/home/amin/Downloads/rapidpro/temba/temba_celery.py", line 23, in <module>
    app.config_from_object('django.conf:settings')
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 299, in config_from_object
    return self.loader.config_from_object(obj, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 145, in config_from_object
    self._conf = force_mapping(obj)
  File "/usr/local/lib/python2.7/dist-packages/celery/datastructures.py", line 52, in force_mapping
    return DictAttribute(m) if not isinstance(m, Mapping) else m
  File "/usr/lib/python2.7/abc.py", line 131, in __instancecheck__
    subclass = getattr(instance, '__class__', None)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 225, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings

**Comment by norkans7** [comment]
It seems you did not symlink the settings as described on the section "clone rapidpro" http://rapidpro.github.io/rapidpro/docs/development/

also consider using virtual environment and activate it before syncdb
