### ISSUE TITLE
Outdated Kombu library

### ISSUE THREAD

**Issue by bruskiza** [rapidpro/rapidpro#219]
The current Kombu library listed in `pip-freeze.txt` is 

```
kombu==3.0.16
```

When doing a `./manage.py syndb` with this, gives the following error on a fresh clone:

```
bru:rapidpro bruce$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/bruce/git/rapidpro/temba/__init__.py", line 5, in <module>
    from .temba_celery import app as celery_app
  File "/Users/bruce/git/rapidpro/temba/temba_celery.py", line 5, in <module>
    from celery import Celery
  File "/usr/local/lib/python2.7/site-packages/celery/__compat__.py", line 141, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python2.7/site-packages/celery/app/__init__.py", line 15, in <module>
    from celery import _state
  File "/usr/local/lib/python2.7/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 23, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python2.7/site-packages/kombu/entity.py", line 10, in <module>
    from .abstract import MaybeChannelBound
  File "/usr/local/lib/python2.7/site-packages/kombu/abstract.py", line 12, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 24, in <module>
    from .log import get_logger
  File "/usr/local/lib/python2.7/site-packages/kombu/log.py", line 7, in <module>
    from .utils import cached_property
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 17, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name _uuid_generate_random
bru:rapidpro bruce$ 
```

Changing kombu to version `3.0.30` in `pip-freeze.txt` fixes this.

As per this stackoverflow post: http://stackoverflow.com/questions/34198538/cannot-import-name-uuid-generate-random-in-heroku-django

**Comment by ericnewcomer** [comment]
This has been fixed.
