### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by Haythamamin** [rapidpro/rapidpro#230]
So I encounter this error every time I try to send an SMS or visit a flow page:

Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner return func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view return self.dispatch(request, *args, **kwargs)
File "/var/www/rapidpro/src/smartmin/smartmin/views.py", line 148, in dispatch return wrapper(request, *args, **kwargs)
File "/var/www/rapidpro/src/smartmin/smartmin/views.py", line 144, in wrapper return super(SmartView, self).dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch return handler(request, *args, **kwargs)
File "/var/www/rapidpro/temba/flows/views.py", line 374, in get revisions = [revision.as_json() for 
revision in flow.revisions.all().order_by('-created_on')[:25]]
File "/var/www/rapidpro/temba/flows/models.py", line 2760, in as_json created_on=datetime_to_str(self.created_on),
File "/var/www/rapidpro/temba/utils/__init__.py", line 65, in datetime_to_str date_obj = timezone.localtime(date_obj, tz)
File "/usr/local/lib/python2.7/dist-packages/django/utils/timezone.py", line 309, in localtime value = value.astimezone(timezone)
ValueError: astimezone() cannot be applied to a naive datetime

I had the Use_TZ set to None, and I changed to default still no luck.

**Comment by Haythamamin** [comment]
I found the problem, after setting TZ = none I had to specify the TZ in apache.conf. Although I was running fine but that solved the error.
