### ISSUE TITLE
syncdb killed

### ISSUE THREAD

**Issue by Hojalab** [rapidpro/rapidpro#258]
Apply all migrations: msgs
Running migrations:
  Rendering model states. killed

**Comment by nicpottier** [comment]
Sounds like you are running out of RAM and the kernel is killing the process.

**Comment by Hojalab** [comment]
thanks for replying i added ram but i got this error 

line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 102, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 127, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 83, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/operations.py", line 218, in last_executed_query
    return cursor.query.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte


now am solving this too

**Comment by Hojalab** [comment]
export LC_CTYPE="en_US.UTF-8"
i did this hope its working

**Comment by Hojalab** [comment]
No Its Not ,

**Comment by nicpottier** [comment]
The same error about decoding bytes?

**Comment by Hojalab** [comment]
No , But I Managed To Ignore The Error by using coverage with test data and by egnoring couple of migrations

**Comment by Hojalab** [comment]
Still Getting Different Error ,, 
 for migration in self.loader.graph.forwards_plan(target):
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/graph.py", line 139, in forwards_plan
    self.ensure_not_cyclic(node, lambda x: (parent.key for parent in self.node_map[x].parents))
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/graph.py", line 196, in ensure_not_cyclic
    raise CircularDependencyError(", ".join("%s.%s" % n for n in cycle))
CircularDependencyError: msgs.0058_update_triggers

**Comment by Hojalab** [comment]
Found Out When The Migration Reach 0057 Thats Where The Issue is  , Here is The Log 
Applying msgs.0057_update_triggers...Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 210, in run_tests
    old_config = self.setup_databases()
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 166, in setup_databases
    **kwargs
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 370, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 368, in create_test_db
    test_flush=not keepdb,
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 102, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 127, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
DataError: invalid byte sequence for encoding "UTF8": 0x8b

**Comment by Hojalab** [comment]
Pass This , Solved With The Old Merge ,, Thanks  , am checking on another issue .
