### ISSUE TITLE
Coverage Test 

### ISSUE THREAD

**Issue by pesaply** [rapidpro/rapidpro#259]
When Trying To Populate migrations With Coverage i get this 
InternalError: cannot drop function temba_call_on_change() because other objects depend on it
DETAIL:  trigger temba_call_on_change_trg on table msgs_call depends on function temba_call_on_change()
trigger temba_call_on_truncate_trg on table msgs_call depends on function temba_call_on_change()
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

**Comment by Hojalab** [comment]
Here Is The Whole Log 
  Applying locations.0005_auto_20160414_0642... OK
  Applying msgs.0058_update_triggers...Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 210, in run_tests
    old_config = self.setup_databases()
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 166, in setup_databases
    **kwargs
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/test/runner.py", line 370, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 368, in create_test_db
    test_flush=not keepdb,
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 102, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 127, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/smspro/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
InternalError: cannot drop function temba_call_on_change() because other objects depend on it
DETAIL:  trigger temba_call_on_change_trg on table msgs_call depends on function temba_call_on_change()
trigger temba_call_on_truncate_trg on table msgs_call depends on function temba_call_on_change()
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

**Comment by nicpottier** [comment]
What demo data?

**Comment by Hojalab** [comment]
Sorry Not Demo Data ,  i meant Test Migration

**Comment by Hojalab** [comment]
coverage  run manage.py test --noinput

**Comment by Hojalab** [comment]
Somehow after managed to sync all the data i still got this  	
User matching query does not exist. when trying to navigate to org/manage/

**Comment by nicpottier** [comment]
Sounds like you don't have any users in your database.

**Comment by Hojalab** [comment]
But The Sync Was A Success , i even droped The Db , and create new user ,

**Comment by ericnewcomer** [comment]
Connect to your database and look at auth_users. Make sure your Anonymous user has an id of -1.
