### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by amechax** [rapidpro/rapidpro#773]
I get this error when trying to run migrate

# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/root/rapidpro/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/rapidpro/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/root/rapidpro/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/rapidpro/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/root/rapidpro/env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/rapidpro/temba/archives/models.py", line 71
    **self.get_s3_location(),
     ^
SyntaxError: invalid syntax

**Comment by rowanseymour** [comment]
We dropped support for Python 2 a while ago - please use Python 3.6 as that's what we test on
