### ISSUE TITLE
Flow's results content not being displayed.

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#995]
# Description
Flow's results option only generates all available data and graphics once the user account is set to use English.

Correct content displayed when user account uses English:
![image](https://user-images.githubusercontent.com/35577716/61372556-e0ec6080-a86d-11e9-9252-b3714dd82715.png)

Incomplete content displayed when user account uses any other language:
![image](https://user-images.githubusercontent.com/35577716/61372644-1db85780-a86e-11e9-8f3a-455104ea52c2.png)

**Comment by WilliamTales** [comment]
New flow editor presents the same behavior.

**Comment by rowanseymour** [comment]
@WilliamTales see any javascript errors in the browser console?

**Comment by WilliamTales** [comment]
Hey @rowanseymour, here's the browser console log for a user set to use not English:
```
Intercooler Error : SyntaxError: Unexpected token ,                               b81bc0b02a8c.js:1658

SyntaxError: Unexpected token ,
    at eval (<anonymous>)
    at Function.globalEval (https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.js:545:5)
    at e.fn.init.domManip (https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.js:5677:16)
    at e.fn.init.append (https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.js:5453:15)
    at doSwap (https://rapidpro.ilhasoft.mobi/sitestatic/CACHE/js/b81bc0b02a8c.js:1785:431)
    at https://rapidpro.ilhasoft.mobi/sitestatic/CACHE/js/b81bc0b02a8c.js:1788:107
    at e (https://rapidpro.ilhasoft.mobi/sitestatic/CACHE/js/b81bc0b02a8c.js:3711:339)
```
For user using English nothing pops.
